# Generated by Django 6.0.1 on 2026-01-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_full_name_student_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_streak',
            field=models.IntegerField(default=0, verbose_name='Current Streak (days)'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_quiz_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Quiz Date'),
        ),
        migrations.AddField(
            model_name='student',
            name='longest_streak',
            field=models.IntegerField(default=0, verbose_name='Longest Streak (days)'),
        ),
    ]
