# Generated by Django 6.0.1 on 2026-01-31 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_language'),
        ('students', '0004_student_current_streak_student_last_quiz_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Январь 2026', 'Семестр 1'", max_length=100, verbose_name='Season Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Only one season can be active at a time per mentor', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='mentors.mentor', verbose_name='Mentor')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ranked_quizzes', models.IntegerField(default=0, verbose_name='Total Ranked Quizzes')),
                ('total_score', models.IntegerField(default=0, verbose_name='Total Score')),
                ('total_possible', models.IntegerField(default=0, verbose_name='Total Possible Score')),
                ('avg_percentage', models.FloatField(default=0.0, verbose_name='Average Percentage')),
                ('rating_score', models.FloatField(default=0.0, help_text='Calculated: avg_percentage × (1 + min(total_quizzes/10, 1) × 0.5)', verbose_name='Rating Score')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='students.season', verbose_name='Season')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_ratings', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Season Rating',
                'verbose_name_plural': 'Season Ratings',
                'ordering': ['-rating_score'],
            },
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('mentor', 'is_active'), name='one_active_season_per_mentor'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonrating',
            unique_together={('season', 'student')},
        ),
    ]
