# Generated by Django 6.0.1 on 2026-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_language'),
        ('students', '0005_add_season_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['mentor', 'joined_at'], name='students_st_mentor__68ccd9_idx'),
        ),
    ]
