# Generated by Django 6.0.1 on 2026-02-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_students_st_mentor__68ccd9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonrating',
            name='earliest_attempt_at',
            field=models.DateTimeField(blank=True, help_text='Earliest finished_at among valid ranked attempts (for tiebreaking)', null=True, verbose_name='Earliest Attempt'),
        ),
    ]
