# Generated by Django 6.0.1 on 2026-01-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quizanswer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=999),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('ranked', 'Ranked')], default='practice', max_length=20),
        ),
    ]
