# Generated by Django 6.0.1 on 2026-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_language'),
        ('quizzes', '0003_quiz_available_from_quiz_available_until_and_more'),
        ('students', '0005_add_season_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['mentor', 'is_active', 'quiz_type'], name='quizzes_qui_mentor__27d7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_type', 'available_until'], name='quizzes_qui_quiz_ty_61a856_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['created_at'], name='quizzes_qui_created_48c994_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'quiz'], name='quizzes_qui_student_2698e5_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'finished_at'], name='quizzes_qui_quiz_id_37c935_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['finished_at'], name='quizzes_qui_finishe_0bfe12_idx'),
        ),
    ]
