# Generated by Django 6.0.1 on 2026-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
        ('materials', '0002_material_materials_m_topic_i_c03f8e_idx'),
        ('students', '0005_add_season_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['material', 'downloaded_at'], name='downloads_d_materia_2f7d44_idx'),
        ),
        migrations.AddIndex(
            model_name='download',
            index=models.Index(fields=['downloaded_at'], name='downloads_d_downloa_e646f3_idx'),
        ),
    ]
