# Generated by Django 6.0.1 on 2026-01-23 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question Text')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mentors.mentor')),
            ],
            options={
                'verbose_name': 'Anonymous Question',
                'verbose_name_plural': 'Anonymous Questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
