# Generated by Django 6.0.1 on 2026-01-26 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('students', '0002_student_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='students.student', verbose_name='Student (Anonymous)'),
        ),
    ]
