# Generated by Django 6.0.1 on 2026-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_language'),
        ('questions', '0002_question_student'),
        ('students', '0005_add_season_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['mentor', 'is_answered'], name='questions_q_mentor__cc3f34_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='questions_q_created_d1d888_idx'),
        ),
    ]
