# Generated by Django 6.0.1 on 2026-02-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_questions_q_mentor__cc3f34_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Reply Time'),
        ),
        migrations.AddField(
            model_name='question',
            name='reply_text',
            field=models.TextField(blank=True, default='', verbose_name='Reply Text'),
        ),
    ]
