# Generated by Django 6.0.1 on 2026-02-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_replied_at_question_reply_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Student's Message ID"),
        ),
    ]
