# Generated by Django 6.0.1 on 2026-02-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='student_telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Student's Telegram ID"),
        ),
    ]
