TEXTS = {
    "ru": {
        # ===== LANGUAGE =====
        "choose_language": "🌐 Выберите язык:",
        "language_changed": "✅ Язык изменён на русский",
        "btn_language": "🌐 Язык",

        # ===== MONTHS =====
        "month_1": "Январь",
        "month_2": "Февраль",
        "month_3": "Март",
        "month_4": "Апрель",
        "month_5": "Май",
        "month_6": "Июнь",
        "month_7": "Июль",
        "month_8": "Август",
        "month_9": "Сентябрь",
        "month_10": "Октябрь",
        "month_11": "Ноябрь",
        "month_12": "Декабрь",

        # ===== START =====
        "welcome_mentor": "👋 Добро пожаловать, {name}!\n\nВы можете загружать и управлять учебными материалами.",
        "welcome_student": "👋 Добро пожаловать в StudyMate!\n\n📚 Ваш ментор: {name}\n\n<b>Возможности бота:</b>\n📚 Учебные материалы — скачивайте файлы и документы\n📝 Квизы — проходите рейтинговые и практические тесты\n❓ Вопросы — задавайте вопросы ментору анонимно\n🏆 Рейтинг — следите за своими результатами",
        "access_denied": "⛔ Доступ запрещён.\n\nВы должны быть участником группы курса.\nОбратитесь к вашему ментору.",
        
        # ===== MENU BUTTONS =====
        "btn_upload": "📤 Загрузить",
        "btn_manage": "📂 Управление",
        "btn_view": "📚 Материалы",
        "btn_materials_menu": "📚 Материалы",
        "btn_statistics": "📊 Статистика",
        "btn_questions": "❓ Вопросы",
        "btn_lesson_materials": "📚 Материалы",
        "btn_ask_question": "❓ Задать вопрос",
        "btn_cancel": "❌ Отмена",
        "btn_back_menu": "⬅️ Назад",
        "btn_profile": "👤 Профиль",

        # ===== MATERIALS SUBMENU =====
        "materials_submenu_header": "📚 <b>Управление материалами</b>\n\nВыберите действие:",

        # ===== STUDENT PROFILE =====
        "profile_setup_welcome": "📝 Для учета успеваемости введите ваше ФИО.\n\nℹ️ <b>Важно:</b>\n• Ваше имя увидит только ваш ментор\n• В рейтинге для других студентов вы останетесь анонимным\n• Вы сможете изменить ФИО в любой момент",
        "profile_enter_fullname": "📝 Введите ваше ФИО:\n\n<i>Можно на кириллице или латинице</i>",
        "profile_name_too_short": "❌ ФИО слишком короткое. Введите минимум 3 символа.",
        "profile_name_too_long": "❌ ФИО слишком длинное. Максимум 200 символов.",
        "profile_name_invalid": "❌ ФИО содержит недопустимые символы. Используйте только буквы, пробелы и дефисы.",
        "profile_completed": "✅ <b>Профиль заполнен!</b>\n\n📝 Ваше ФИО: <b>{name}</b>\n\nТеперь вы можете пользоваться всеми функциями бота.",
        "profile_view": "👤 <b>Ваш профиль</b>\n\n📝 ФИО: <b>{name}</b>\n📱 Telegram: {telegram}\n📅 В боте с: {joined}\n🌐 Язык: {language}\n📊 Ментор: {mentor}\n\n📈 <b>Статистика</b>\n━━━━━━━━━━━━━━━\n📚 Всего квизов: <b>{total_quizzes}</b>\n  ├ 🏆 Ranked: {total_ranked}\n  └ 📝 Practice: {total_practice}\n\n📊 Средний результат: <b>{avg_percentage}%</b>\n🎯 Лучший результат: <b>{best_score}/{best_total}</b> ({best_percentage}%)\n\n{streak_emoji} <b>Серия</b>\n━━━━━━━━━━━━━━━\n🔥 Текущая: <b>{current_streak} дн.</b>\n🏅 Рекорд: <b>{longest_streak} дн.</b>",
        "profile_not_set": "не указано",
        "btn_use_telegram_name": "✅ Использовать имя из Telegram",
        "btn_edit_profile": "✏️ Изменить ФИО",
        "profile_edit_prompt": "✏️ Введите новое ФИО:",
        "profile_updated": "✅ ФИО обновлено!",
        
        # ===== UPLOAD =====
        "choose_topic_upload": "📤 Выберите тему для загрузки:",
        "create_new_topic": "➕ Создать тему",
        "enter_topic_name": "📝 Введите название темы (например: HTML, CSS, JavaScript):",
        "topic_created": "✅ Тема «{name}» создана!\n\nТеперь используйте 📤 Загрузить для добавления файлов.",
        "send_file": "📁 Тема: {name}\n\n📎 Отправьте файл (PDF, Word, изображение и т.д.)",
        "file_received": "📝 Файл получен: {name}\n\nВведите название для этого материала:",
        "photo_received": "📝 Фото получено!\n\nВведите название для этого материала:",
        "material_added": "✅ Материал добавлен!\n\n📁 Тема: {topic}\n📄 Название: {title}",
        
        # ===== MANAGE =====
        "no_topics": "📭 Тем пока нет. Используйте 📤 Загрузить для создания.",
        "select_topic_manage": "📂 Выберите тему для управления:",
        "tap_to_delete": "📂 <b>{name}</b>\n\nНажмите на файл для удаления:",
        "no_topics_left": "📭 Тем не осталось.",
        
        # ===== DELETE CONFIRMATION =====
        "confirm_delete_file": "🗑️ <b>Удалить этот файл?</b>\n\n📄 {title}",
        "btn_yes_delete": "✅ Да",
        "btn_no_cancel": "❌ Нет",
        "file_deleted": "✅ Файл удалён!",
        "confirm_delete_topic": "⚠️ <b>Удалить всю тему?</b>\n\n📁 {name}\n📄 {count} файл(ов) будет удалено\n\nЭто действие нельзя отменить!",
        "btn_yes_delete_all": "✅ Да, удалить",
        "topic_deleted": "✅ Тема «{name}» удалена!",
        
        # ===== VIEW MATERIALS =====
        "your_materials": "📚 <b>Ваши материалы:</b>",
        "lesson_materials": "📚 <b>Учебные материалы</b>\n\nВыберите тему:",
        "no_materials": "📭 Материалов пока нет.",
        "no_materials_yet": "📭 Материалов пока нет.\n\nЗагляните позже!",
        "topic_files": "📂 <b>{name}</b>\n\n📄 {count} материал(ов)\n\nНажмите для скачивания:",
        "file_sent": "✅ Отправлено!",
        "file_not_found": "❌ Файл не найден",
        "btn_back": "⬅️ Назад",
        "btn_back_topics": "⬅️ К темам",
        "btn_prev": "◀️",
        "btn_next": "▶️",
        
        # ===== STATISTICS =====
        "statistics": "📊 <b>Статистика</b>\n\n",
        "stats_students": "👥 Учеников: <b>{count}</b>\n",
        "stats_topics": "📁 Тем: <b>{count}</b>\n",
        "stats_materials": "📄 Материалов: <b>{count}</b>\n",
        "stats_questions": "❓ Вопросов: <b>{total}</b>",
        "stats_unanswered": " ({count} без ответа)",
        "stats_active_today": "📈 Активных сегодня: <b>{count}</b>\n",
        "stats_active_week": "📅 Активных за неделю: <b>{count}</b>\n",
        "stats_popular": "\n🔥 <b>Популярные материалы:</b>\n",
        "stats_popular_item": "{num}. {title} — {count} скач.\n",
        
        # ===== QUESTIONS =====
        "write_question": "✏️ Напишите ваш вопрос.\n\nВаше имя НЕ будет показано учителю.",
        "question_sent": "✅ Вопрос отправлен!",
        "cancelled": "❌ Отменено",
        "no_questions": "📭 Новых вопросов нет.\n\nВопросы от учеников появятся здесь.",
        "unanswered_questions": "❓ Вопросов без ответа ({count}):\n\n",
        "anonymous_question": "❓ <b>Анонимный вопрос:</b>\n\n{text}",
        "btn_answered": "✅ Отвечено",
        "btn_reply": "💬 Ответить",
        "marked_answered": "✅ Отмечено!",
        "and_more": "...и ещё {count}.",
        "write_reply": "✏️ Напишите ваш ответ на вопрос:\n\n<b>Вопрос:</b> {text}",
        "reply_sent": "✅ Ответ отправлен ученику!",
        "mentor_reply": "💬 <b>Ответ от вашего ментора:</b>\n\n{text}",
        "question_not_found": "❌ Вопрос не найден",
        
        # ===== ERRORS =====
        "error": "⚠️ Ошибка. Используйте /start",
        "not_assigned": "⚠️ Вы не привязаны к ментору. Используйте /start",
        "throttle_warning_1": "⏱ Пожалуйста, подождите немного перед следующим действием",
        "throttle_warning_2": "⏱ Вы отправляете сообщения слишком быстро. Подождите немного.",
        "throttle_warning_3": "⚠️ Пожалуйста, не спамьте. Подождите несколько секунд.",

        # ===== MANAGE FILES =====
        "btn_delete_topic": "🗑️ Удалить тему",

        # ===== QUIZZES =====
        "btn_quizzes": "📝 Квизы",
        "no_quizzes": "📭 Квизов пока нет.",
        "select_quiz": "📝 Выберите квиз:",
        "upload_quiz": "📄 Отправьте .txt файл с квизом.",
        "quiz_uploaded": "✅ Квиз «{title}» создан!\n\n📊 Вопросов: {count}",
        "quiz_parse_error": "❌ Ошибка парсинга файла. Проверьте формат.",
        "quiz_question": "❓ <b>Вопрос {current}/{total}</b>\n\n{text}\n\nA) {a}\nB) {b}\nC) {c}\nD) {d}",
        "quiz_finished": "🎉 <b>Квиз завершён!</b>\n\n✅ Ваш результат: <b>{score}/{total}</b>\n📊 Среднее по группе: <b>{avg}</b>",
        "quiz_review_header": "\n\n📋 <b>Ваши ответы:</b>\n",
        "quiz_review_header_page": "\n\n📋 <b>Ваши ответы (стр. {page}/{total_pages}):</b>\n",
        "quiz_review_correct": "✅ {num}. {question}\n   Ваш ответ: <b>{answer}</b> ✓\n",
        "quiz_review_wrong": "❌ {num}. {question}\n   Ваш ответ: <b>{answer}</b> | Правильно: <b>{correct}</b>\n",
        "quiz_results": "📊 <b>Результаты: {title}</b>\n\n👥 Прошли: {attempts}\n📈 Средний балл: {avg}\n\n🏆 <b>Топ учеников:</b>\n{top}",
        "quiz_no_attempts": "Ещё никто не прошёл этот квиз.",
        "quiz_your_result": "Ваш результат: {score}/{total}",
        "quiz_not_attempted": "Ещё не пройден",
        "quiz_already_taken": "⚠️ Вы уже проходили этот квиз.\n\nВаш результат: {score}/{total}",
        "quiz_view_answers": "📋 Посмотреть ответы",
        "quiz_retake": "🔄 Пройти заново",
        "quiz_time_expired": "⏱ Время вышло",
        "quiz_seconds": "сек.",
        "quiz_in_progress": "⏳ Вы сейчас проходите квиз!\n\nСначала завершите текущий квиз, чтобы получить доступ к другим функциям бота.",
        "btn_upload_quiz": "📤 Загрузить квиз",
        "btn_delete_quiz": "🗑️ Удалить квиз",
        "btn_quiz_results": "📊 Результаты",
        "btn_save_quiz": "✅ Сохранить",
        "btn_cancel_quiz": "❌ Отмена",
        "btn_replace_quiz": "🗄️ Архивировать и заменить",
        "btn_copy_quiz": "➕ Создать копию",
        "btn_archive_quiz": "🗄️ Архивировать",
        "btn_unarchive_quiz": "♻️ Вернуть из архива",
        "btn_restart_quiz": "🔄 Перезапустить квиз",
        "btn_manage_questions": "📋 Управление вопросами",
        "btn_export_results": "📤 Экспорт результатов",
        "btn_add_question": "➕ Добавить вопрос",
        "btn_edit_question": "✏️ Редактировать",
        "btn_delete_question": "🗑️ Удалить вопрос",
        "btn_back_quiz": "⬅️ К квизу",
        "btn_back_questions": "⬅️ К списку",
        "btn_edit_text": "✏️ Текст вопроса",
        "btn_edit_option_a": "A) Вариант A",
        "btn_edit_option_b": "B) Вариант B",
        "btn_edit_option_c": "C) Вариант C",
        "btn_edit_option_d": "D) Вариант D",
        "btn_edit_correct": "✅ Правильный ответ",
        "confirm_delete_quiz": "🗑️ <b>Удалить квиз?</b>\n\n📝 {title}\n❓ {count} вопросов\n\nВсе результаты учеников будут удалены!",
        "quiz_preview": "👀 <b>Предпросмотр квиза</b>\n\n📝 {title}\n📌 Тема: {topic}\n❓ Вопросов: {count}\n\n{preview}",
        "quiz_preview_question": "1) {text}\nA) {a}\nB) {b}\nC) {c}\nD) {d}",
        "quiz_duplicate_found": "⚠️ Квиз с названием «{title}» уже существует. Выберите действие:",
        "quiz_ready_actions": "Выберите действие в меню.",
        "confirm_archive_quiz": "🗄️ <b>Архивировать квиз?</b>\n\n📝 {title}\n❓ {count} вопросов",
        "confirm_restart_quiz": "🔄 <b>Перезапустить квиз?</b>\n\n📝 {title}\n\n⚠️ Все попытки студентов будут удалены!\n🔀 Вопросы будут перемешаны случайным образом.\n\nПродолжить?",
        "quiz_restarted": "✅ Квиз перезапущен! Вопросы перемешаны.",
        "quiz_deleted": "✅ Квиз удалён!",
        "quiz_archived": "🗄️ Квиз архивирован.",
        "quiz_unarchived": "♻️ Квиз возвращён из архива.",
        "quiz_questions_title": "📋 <b>{title}</b>\n\nВопросов: {count}",
        "quiz_question_detail": "❓ <b>Вопрос</b>\n\n{question}\n\nA) {a}\nB) {b}\nC) {c}\nD) {d}\n\n<b>Правильный:</b> {correct}",
        "enter_question_text": "❓ Введите текст вопроса:",
        "enter_option_a": "A) Введите вариант A:",
        "enter_option_b": "B) Введите вариант B:",
        "enter_option_c": "C) Введите вариант C:",
        "enter_option_d": "D) Введите вариант D:",
        "enter_correct_option": "Введите букву правильного ответа (A/B/C/D):",
        "invalid_correct_option": "❌ Введите A, B, C или D.",
        "question_added": "✅ Вопрос добавлен!",
        "confirm_delete_question": "🗑️ <b>Удалить вопрос?</b>\n\n{text}",
        "question_deleted": "✅ Вопрос удалён!",
        "question_updated": "✅ Вопрос обновлён!",
        "quiz_edit_prompt": "✏️ Что хотите изменить?",
        "quiz_export_ready": "📤 Готово! Файл с результатами.",
        "quiz_export_empty": "🗒️ Пока нет попыток.",
        "quiz_mentor_list": "📝 <b>Ваши квизы:</b>",
        "quiz_item_mentor": "📝 {title} • {questions} вопр. • {attempts} попыток",
        "quiz_item_student": "📝 {title}",
        "quiz_item_student_score": "📝 {title} • {score}/{total}",

        # ===== LEADERBOARD =====
        "btn_leaderboard": "🏆 Рейтинг",
        "leaderboard_title": "🏆 <b>Рейтинг учеников</b>\n\n",
        "leaderboard_entry": "{medal} {name} — <code>{score}</code>\n",
        "leaderboard_you": "{medal} <b>ВЫ</b> — <code>{score}</code>\n",
        "leaderboard_footer": "",
        "leaderboard_empty": "📭 Рейтинг пуст. Пройдите квизы чтобы попасть в топ!",
        "leaderboard_your_rank": "\n<b>━━━━━━━━━━━━━━━</b>\n📍 <b>Ваша позиция:</b> #{rank}\n💯 <b>Балл:</b> <code>{score}</code>",
        "leaderboard_separator_top3": "\n<b>━━━━━━━━━━━━━━━</b>\n",
        "leaderboard_mentor_title": "🏆 <b>Рейтинг учеников</b>\n\n",
        "leaderboard_mentor_entry": "{rank}. {name} — {score} балл.\n   📊 {percentage}% среднее • {quizzes} квиз.\n",
        "leaderboard_mentor_pagination": "Всего студентов: {total} • Страница {page}/{total_pages}",

        # Animal names for anonymization
        "animal_fox": "🦊 Лиса",
        "animal_bear": "🐻 Медведь",
        "animal_eagle": "🦅 Орёл",
        "animal_wolf": "🐺 Волк",
        "animal_lion": "🦁 Лев",
        "animal_tiger": "🐯 Тигр",
        "animal_panda": "🐼 Панда",
        "animal_koala": "🐨 Коала",
        "animal_owl": "🦉 Сова",
        "animal_shark": "🦈 Акула",
        "animal_cheetah": "🐆 Гепард",
        "animal_giraffe": "🦒 Жираф",
        "animal_elephant": "🐘 Слон",
        "animal_cat": "🐱 Кот",
        "animal_kangaroo": "🦘 Кенгуру",

        # ===== RANKED/PRACTICE QUIZZES =====
        "btn_publish_practice": "📚 Опубликовать как Практический",
        "btn_publish_ranked": "🏆 Опубликовать как Рейтинговый",
        "btn_keep_draft": "🗃 Оставить как Черновик",
        "choose_publish_mode": "📤 <b>Выберите режим публикации:</b>\n\n📚 <b>Практический</b> — неограниченные попытки, не влияет на рейтинг\n🏆 <b>Рейтинговый</b> — 1 попытка, влияет на рейтинг, ограниченное время",
        "btn_start_now": "▶️ Начать сейчас",
        "btn_schedule_start": "🗓 Выбрать время",
        "choose_ranked_start": "🗓 <b>Когда начать рейтинговый квиз?</b>\n\n▶️ Начать сейчас — доступен 48 часов\n🗓 Выбрать время — запланировать на будущее",
        "enter_ranked_start_time": "🗓 Введите дату и время начала\n\nФормат: <code>ДД.ММ ЧЧ:ММ</code>\nПример: <code>30.01 18:00</code>",
        "invalid_datetime_format": "❌ Неверный формат даты.\n\nИспользуйте: ДД.ММ ЧЧ:ММ\nПример: 30.01 18:00",
        "quiz_scheduled": "✅ Рейтинговый квиз запланирован!\n\n📝 {title}\n📅 Начало: {start}\n⏰ Окончание: {end}\n\nУченики смогут пройти квиз в это время.",
        "quiz_published_practice": "✅ Практический квиз опубликован!\n\n📝 {title}\nУченики могут проходить его неограниченное количество раз.",
        "quiz_not_started": "⏳ Этот квиз ещё не начался.\n\n📅 Начало: {start}",
        "quiz_expired": "⏰ Время для прохождения этого квиза истекло.",
        "quiz_max_attempts": "⚠️ Вы уже использовали все попытки для этого квиза.",
        "ranked_section_header": "🏆 <b>Рейтинговые квизы</b>\n\n",
        "practice_section_header": "\n📚 <b>Практические квизы</b>\n\n",
        "quiz_ranked_badge": "🏆",
        "quiz_practice_badge": "📚",
        "quiz_exam_mode_result": "🎉 <b>Квиз завершён!</b>\n\n✅ Ваш результат: <b>{score}/{total}</b>\n\n📊 Правильные ответы будут показаны после окончания времени квиза.",
        "no_ranked_quizzes": "📭 Сейчас нет активных рейтинговых квизов.",
        "no_practice_quizzes": "📭 Практических квизов пока нет.",
        "new_ranked_quiz_notification": "🏆 <b>Новый рейтинговый квиз!</b>\n\n📝 {title}\n📅 Начало: {start}\n⏰ Окончание: {end}\n\nУ вас есть только <b>одна попытка</b>. Результат повлияет на рейтинг!",

        # ===== MENU HEADERS =====
        "quiz_management_header": "📝 <b>Управление квизами</b>\n\nВыберите категорию:",
        "quiz_student_header": "📝 <b>Квизы</b>\n\nВыберите категорию:",
        "btn_active_quizzes": "📝 Активные квизы",
        "btn_archived_quizzes": "🗄️ Архивированные квизы",
        "btn_ranked_quizzes": "🏆 Рейтинговые квизы",
        "btn_practice_quizzes": "📚 Практические квизы",
        "active_quizzes_header": "📝 <b>Активные квизы</b>",
        "archived_quizzes_header": "🗄️ <b>Архивированные квизы</b>",
        "ranked_quizzes_header": "🏆 <b>Рейтинговые квизы</b>",
        "practice_quizzes_header": "📚 <b>Практические квизы</b>",
        "pagination_info": "<i>Страница {page}/{total} • Всего: {count}</i>",
        "no_active_quizzes": "📭 Активных квизов пока нет.",
        "no_archived_quizzes": "📭 Нет архивированных квизов.",
        "error_mentor_not_found": "⚠️ Ошибка: ментор не найден",
        "btn_back_short": "◀️ Назад",
        "btn_archived_short": "🗄️ Архивированные",
        "btn_active_short": "📝 Активные",
        "btn_ranked_short": "🏆 Рейтинговые",
        "btn_practice_short": "📚 Практические",
    },

    "qq": {
        # ===== LANGUAGE =====
        "choose_language": "🌐 Tildi tanlań:",
        "language_changed": "✅ Til qaraqalpaqshaǵa ózgertildi",
        "btn_language": "🌐 Til",

        # ===== MONTHS =====
        "month_1": "Yanvar",
        "month_2": "Fevral",
        "month_3": "Mart",
        "month_4": "Aprel",
        "month_5": "May",
        "month_6": "Iyun",
        "month_7": "Iyul",
        "month_8": "Avgust",
        "month_9": "Sentyabr",
        "month_10": "Oktyabr",
        "month_11": "Noyabr",
        "month_12": "Dekabr",

        # ===== START =====
        "welcome_mentor": "👋 Xosh kelipsiz, {name}!\n\nSiz oqıw materialların júklewińiz hám basqarıwıńız múmkin.",
        "welcome_student": "👋 StudyMate'ǵa xosh kelipsiz!\n\n📚 Mentorıńız: {name}\n\n<b>Bottıń imkaniyatlari</b>:\n📚 Oqıw materialları — fayllar hám dokumentlerdi júklep alıń\n📝 Kvizler — reytinglik hám praktikalıq testlerden ótiń\n❓ Sorawlar — mentorǵa anonim soraw beriń\n🏆 Reyting — nátiyjelerińiz benen tanısıń",
        "access_denied": "⛔ Kiriw qadaǵan etilgen.\n\nSiz kurs toparınıń aǵzası bolıwıńız kerek.\nMentorińizǵa xabarlasıń.",
        
        # ===== MENU BUTTONS =====
        "btn_upload": "📤 Júklew",
        "btn_manage": "📂 Basqarıw",
        "btn_view": "📚 Materiallar",
        "btn_materials_menu": "📚 Materiallar",
        "btn_statistics": "📊 Statistika",
        "btn_questions": "❓ Sorawlar",
        "btn_lesson_materials": "📚 Materiallar",
        "btn_ask_question": "❓ Soraw beriw",
        "btn_cancel": "❌ Biykar etiw",
        "btn_back_menu": "⬅️ Artqa",
        "btn_profile": "👤 Profil",

        # ===== MATERIALS SUBMENU =====
        "materials_submenu_header": "📚 <b>Materiallar basqarıwı</b>\n\nÁmeldi tańlań:",

        # ===== STUDENT PROFILE =====
        "profile_setup_welcome": "📝 Úlgeriw esabı ushın atıńız hám familiyańızdı kirgiziń.\n\nℹ️ <b>Mańızlı:</b>\n• Atıńızdı tek mentorıńız kóredi\n• Reytingde basqa oqıwshılar ushın siz anonim bolasız\n• Atıńızdı qálegen waqıtta ózgertiwńiz múmkin",
        "profile_enter_fullname": "📝 Tolıq atıńızdı kirgiziń:\n\n<i>Kirillica yaki latinicada múmkin</i>",
        "profile_name_too_short": "❌ At juda qısqa. Keminde 3 hárip kirgiziń.",
        "profile_name_too_long": "❌ At juda uzın. Maksimum 200 hárip.",
        "profile_name_invalid": "❌ Atda ruqsat etilmegen belgiler bar. Tek hárip, probel hám tire paydalanıń.",
        "profile_completed": "✅ <b>Profil toltırıldı!</b>\n\n📝 Sizdiń atıńız: <b>{name}</b>",
        "profile_view": "👤 <b>Sizdiń profilińiz</b>\n\n📝 Tolıq atı: <b>{name}</b>\n📱 Telegram: {telegram}\n📅 Botta: {joined}\n🌐 Til: {language}\n📊 Mentor: {mentor}\n\n📈 <b>Statistika</b>\n━━━━━━━━━━━━━━━\n📚 Barlıq kvizler: <b>{total_quizzes}</b>\n  ├ 🏆 Reytinglik: {total_ranked}\n  └ 📝 Praktikalıq: {total_practice}\n\n📊 Ortasha nátiyje: <b>{avg_percentage}%</b>\n🎯 Eń jaqsı nátiyje: <b>{best_score}/{best_total}</b> ({best_percentage}%)\n\n{streak_emoji} <b>Seriya</b>\n━━━━━━━━━━━━━━━\n🔥 Házirgi: <b>{current_streak} kún</b>\n🏅 Rekord: <b>{longest_streak} kún</b>",
        "profile_not_set": "kórsetilmegen",
        "btn_use_telegram_name": "✅ Telegram atın paydalanıw",
        "btn_edit_profile": "✏️ Atıń ózgertiw",
        "profile_edit_prompt": "✏️ Jańadan tolıq atıńızdı kirgiziń:",
        "profile_updated": "✅ Atıńız jańalandı!",
        
        # ===== UPLOAD =====
        "choose_topic_upload": "📤 Júklew ushın temanı tańlań:",
        "create_new_topic": "➕ Jana tema",
        "enter_topic_name": "📝 Tema atın kirgiziń (máselen: HTML, CSS, JavaScript):",
        "topic_created": "✅ «{name}» teması jaratıldı!\n\nEndi fayllardı qosıw ushın 📤 Júklew knopkasin basıń.",
        "send_file": "📁 Tema: {name}\n\n📎 Fayl jiberiń (PDF, Word, súwret hám t.b.)",
        "file_received": "📝 Fayl qabil etildi: {name}\n\nBul material ushin atama kirgiziń:",
        "photo_received": "📝 Súwret qabıl etildi!\n\nBul material ushın atama kirgiziń:",
        "material_added": "✅ Material qosıldı!\n\n📁 Tema: {topic}\n📄 Atı: {title}",
        
        # ===== MANAGE =====
        "no_topics": "📭 Házirshe temalar joq. Jaratıw ushın 📤 Júklew knopkasin basıń.",
        "select_topic_manage": "📂 Basqarıw ushın temanı tańlań:",
        "tap_to_delete": "📂 <b>{name}</b>\n\nOshırıw ushın fayldı basıń:",
        "no_topics_left": "📭 Temalar qalmadı.",
        
        # ===== DELETE CONFIRMATION =====
        "confirm_delete_file": "🗑️ <b>Bul fayldı óshiresiz be?</b>\n\n📄 {title}",
        "btn_yes_delete": "✅ Awa",
        "btn_no_cancel": "❌ Yaq",
        "file_deleted": "✅ Fayl óshirildi!",
        "confirm_delete_topic": "⚠️ <b>Pútkil temanı óshiresiz be?</b>\n\n📁 {name}\n📄 {count} fayl óshiriledi\n\nBunı qaytarıp bolmaydı!",
        "btn_yes_delete_all": "✅ Awa, óshiriw",
        "topic_deleted": "✅ «{name}» teması óshirildi!",
        
        # ===== VIEW MATERIALS =====
        "your_materials": "📚 <b>Materiallar:</b>",
        "lesson_materials": "📚 <b>Oqiw materialları</b>\n\nTema tanlań:",
        "no_materials": "📭 Házirshe materiallar joq.",
        "no_materials_yet": "📭 Házirshe materiallar joq.\n\nKeyinirek tekseriń!",
        "topic_files": "📂 <b>{name}</b>\n\n📄 {count} material\n\nJúklew ushın basıń:",
        "file_sent": "✅ Jiberildi!",
        "file_not_found": "❌ Fayl tabilmadi",
        "btn_back": "⬅️ Arqaǵa",
        "btn_back_topics": "⬅️ Temalarǵa",
        "btn_prev": "◀️",
        "btn_next": "▶️",
        
        # ===== STATISTICS =====
        "statistics": "📊 <b>Statistika</b>\n\n",
        "stats_students": "👥 Oqıwshılar: <b>{count}</b>\n",
        "stats_topics": "📁 Temalar: <b>{count}</b>\n",
        "stats_materials": "📄 Materiallar: <b>{count}</b>\n",
        "stats_questions": "❓ Sorawlar: <b>{total}</b>",
        "stats_unanswered": " ({count} juwapsız)",
        "stats_active_today": "📈 Búgin aktiv: <b>{count}</b>\n",
        "stats_active_week": "📅 Háptede aktiv: <b>{count}</b>\n",
        "stats_popular": "\n🔥 <b>Kóp tarqalgan materiallar</b>\n",
        "stats_popular_item": "{num}. {title} — {count} júklew\n",
        
        # ===== QUESTIONS =====
        "write_question": "✏️ Sorawıńızdı jazıń.\n\nAtıńız oqıtıwshıǵa KÓRSETILMEYDI",
        "question_sent": "✅ Soraw jiberildi!",
        "cancelled": "❌ Biykar etildi",
        "no_questions": "📭 Jańa sorawlar joq.\n\nOqıwshılardan sorawlar usı jerde payda boladı.",
        "unanswered_questions": "❓ Juwap berilmegen sorawlar ({count}):\n\n",
        "anonymous_question": "❓ <b>Anonim soraw:</b>\n\n{text}",
        "btn_answered": "✅ Juwap berildi",
        "btn_reply": "💬 Juwap beriw",
        "marked_answered": "✅ Belgilendi!",
        "and_more": "...hám jáne {count}.",
        "write_reply": "✏️ Sorawǵa juwabıńızdı jazıń:\n\n<b>Soraw:</b> {text}",
        "reply_sent": "✅ Juwap oqıwshıǵa jiberildi!",
        "mentor_reply": "💬 <b>Mentordan juwap:</b>\n\n{text}",
        "question_not_found": "❌ Soraw tabilmadı",
        
        # ===== ERRORS =====
        "error": "⚠️ Qátelik. /start buyrıgın paydalanıń",
        "not_assigned": "⚠️ Siz mentorǵa biriktirilmegensiz. /start buyrıgın paydalanıń",
        "throttle_warning_1": "⏱ Kelesi ámelden aldın kishkene kútiń",
        "throttle_warning_2": "⏱ Xabarlardi juda tez jiberip atırsız. Kútiń.",
        "throttle_warning_3": "⚠️ Spam etpeń. Bir nеshe sekund kútiń.",

        # ===== MANAGE FILES =====
        "btn_delete_topic": "🗑️ Temani óshiriw",

        # ===== QUIZZES =====
        "btn_quizzes": "📝 Kvizler",
        "no_quizzes": "📭 Házirshe kvizler joq.",
        "select_quiz": "📝 Kvizdi tańlań:",
        "upload_quiz": "📄 Kviz menen .txt fayl jiberiń.",
        "quiz_uploaded": "✅ «{title}» kvizi jaratıldı!\n\n📊 Sorawlar: {count}",
        "quiz_parse_error": "❌ Fayl parsingi qátesi. Formatın tekseriń.",
        "quiz_question": "❓ <b>Soraw {current}/{total}</b>\n\n{text}\n\nA) {a}\nB) {b}\nC) {c}\nD) {d}",
        "quiz_finished": "🎉 <b>Kviz tamamlandı!</b>\n\n✅ Nátiyjeńiz: <b>{score}/{total}</b>\n📊 Ortasha ball: <b>{avg}</b>",
        "quiz_review_header": "\n\n📋 <b>Juwaplarıńız:</b>\n",
        "quiz_review_header_page": "\n\n📋 <b>Juwaplarıńız ({page}/{total_pages}-bet):</b>\n",
        "quiz_review_correct": "✅ {num}. {question}\n   Juwabıńız: <b>{answer}</b> ✓\n",
        "quiz_review_wrong": "❌ {num}. {question}\n   Juwabıńız: <b>{answer}</b> | Durıs: <b>{correct}</b>\n",
        "quiz_results": "📊 <b>Nátiyje: {title}</b>\n\n👥 Ótkenler: {attempts}\n📈 Ortasha ball: {avg}\n\n🏆 <b>Top oqıwshılar:</b>\n{top}",
        "quiz_no_attempts": "Házirshe heshkim bul kvizdi ótpedi.",
        "quiz_your_result": "Nátiyjeńiz: {score}/{total}",
        "quiz_not_attempted": "Házirshe ótilmegen",
        "quiz_already_taken": "⚠️ Siz bul kvizdi álle qashan óttińiz.\n\nNátiyjeńiz: {score}/{total}",
        "quiz_view_answers": "📋 Juwaplardı kóriw",
        "quiz_retake": "🔄 Qaytadan ótiw",
        "quiz_time_expired": "⏱ Waqıt bitti",
        "quiz_seconds": "sek.",
        "quiz_in_progress": "⏳ Siz házir kviz ótip atırsız!\n\nBottıń basqa funkciyalarınan paydalanıw ushın házirgi kvizdi juwmaqlań.",
        "btn_upload_quiz": "📤 Kviz júklew",
        "btn_delete_quiz": "🗑️ Kvizdi óshiriw",
        "btn_quiz_results": "📊 Nátiyje",
        "btn_save_quiz": "✅ Saqlaw",
        "btn_cancel_quiz": "❌ Biykar",
        "btn_replace_quiz": "🗄️ Arhivke salıp almastrıw",
        "btn_copy_quiz": "➕ Nusqa jaratıw",
        "btn_archive_quiz": "🗄️ Arhivke saliw",
        "btn_unarchive_quiz": "♻️ Arhivten qaytarıw",
        "btn_restart_quiz": "🔄 Kvizdi qayta baslaw",
        "btn_manage_questions": "📋 Sorawlar basqarıwı",
        "btn_export_results": "📤 Nátijelerdi eksport",
        "btn_add_question": "➕ Soraw qosıw",
        "btn_edit_question": "✏️ Ózgertiw",
        "btn_delete_question": "🗑️ Sorawdı óshiriw",
        "btn_back_quiz": "⬅️ Kvizge",
        "btn_back_questions": "⬅️ Dizimge",
        "btn_edit_text": "✏️ Soraw teksti",
        "btn_edit_option_a": "A) A nusqa",
        "btn_edit_option_b": "B) B nusqa",
        "btn_edit_option_c": "C) C nusqa",
        "btn_edit_option_d": "D) D nusqa",
        "btn_edit_correct": "✅ Durıs juwap",
        "confirm_delete_quiz": "🗑️ <b>Kvizdi óshiresiz be?</b>\n\n📝 {title}\n❓ {count} soraw\n\nBarlıq nátijeler óshiriledi!",
        "quiz_preview": "👀 <b>Kvizdi kóriw</b>\n\n📝 {title}\n📌 Tema: {topic}\n❓ Sorawlar: {count}\n\n{preview}",
        "quiz_preview_question": "1) {text}\nA) {a}\nB) {b}\nC) {c}\nD) {d}",
        "quiz_duplicate_found": "⚠️ «{title}» atlı kviz bar. Amaldı tańlań:",
        "quiz_ready_actions": "Menyuden amaldı tańlań.",
        "confirm_archive_quiz": "🗄️ <b>Kvizdi arhivke salası́z ba?</b>\n\n📝 {title}\n❓ {count} soraw",
        "confirm_restart_quiz": "🔄 <b>Kvizdi qayta baslaw kerek pe?</b>\n\n📝 {title}\n\n⚠️ Oqıwshılardıń barlıq talabanları óshiriledi!\n🔀 Sorawlar kázdeshelı aralastırıladı.\n\nDawam etesíz be?",
        "quiz_restarted": "✅ Kviz qayta baslandı! Sorawlar aralastırıldı.",
        "quiz_deleted": "✅ Kviz óshirildi!",
        "quiz_archived": "🗄️ Kviz arhivke salındı.",
        "quiz_unarchived": "♻️ Kviz arhivten qaytarıldı.",
        "quiz_questions_title": "📋 <b>{title}</b>\n\nSorawlar: {count}",
        "quiz_question_detail": "❓ <b>Soraw</b>\n\n{question}\n\nA) {a}\nB) {b}\nC) {c}\nD) {d}\n\n<b>Dúris:</b> {correct}",
        "enter_question_text": "❓ Soraw tekstin kirgiziń:",
        "enter_option_a": "A) A nusqa:",
        "enter_option_b": "B) B nusqa:",
        "enter_option_c": "C) C nusqa:",
        "enter_option_d": "D) D nusqa:",
        "enter_correct_option": "Dúris juwaptıń harpin kirgiziń (A/B/C/D):",
        "invalid_correct_option": "❌ A, B, C yaki D kirgiziń.",
        "question_added": "✅ Soraw qosıldı!",
        "confirm_delete_question": "🗑️ <b>Sorawdı óshiresiz be?</b>\n\n{text}",
        "question_deleted": "✅ Soraw óshirildi!",
        "question_updated": "✅ Soraw ózgertildi!",
        "quiz_edit_prompt": "✏️ Neni ózgertemiz?",
        "quiz_export_ready": "📤 Tayyar! Nátijeler faylı.",
        "quiz_export_empty": "🗒️ Házir heshkim tapsırmadı.",
        "quiz_mentor_list": "📝 <b>Sizdiń kvizler:</b>",
        "quiz_item_mentor": "📝 {title} • {questions} soraw • {attempts} talaban",
        "quiz_item_student": "📝 {title}",
        "quiz_item_student_score": "📝 {title} • {score}/{total}",

        # ===== LEADERBOARD =====
        "btn_leaderboard": "🏆 Reyting",
        "leaderboard_title": "🏆 <b>Oqıwshılar reytingi</b>\n\n",
        "leaderboard_entry": "{medal} {name} — <code>{score}</code>\n",
        "leaderboard_you": "{medal} <b>SIZ</b> — <code>{score}</code>\n",
        "leaderboard_footer": "",
        "leaderboard_empty": "📭 Reyting bos. Top-ǵa tusiw ushın reytinglik kvizlerdi ótip shıǵıń!",
        "leaderboard_your_rank": "\n<b>━━━━━━━━━━━━━━━</b>\n📍 <b>Sizdiń ornıńız:</b> #{rank}\n💯 <b>Ball:</b> <code>{score}</code>",
        "leaderboard_separator_top3": "\n<b>━━━━━━━━━━━━━━━</b>\n",
        "leaderboard_mentor_title": "🏆 <b>Oqıwshılar reytingi</b>\n\n",
        "leaderboard_mentor_entry": "{rank}. {name} — {score} ball\n   📊 {percentage}% ortasha • {quizzes} kviz\n",
        "leaderboard_mentor_pagination": "Barlıǵı: {total} • Bet {page}/{total_pages}",

        # Animal names for anonymization
        "animal_fox": "🦊 Túlki",
        "animal_bear": "🐻 Ayıw",
        "animal_eagle": "🦅 Búrkіt",
        "animal_wolf": "🐺 Qasqır",
        "animal_lion": "🦁 Arıslan",
        "animal_tiger": "🐯 Jolbarıs",
        "animal_panda": "🐼 Panda",
        "animal_koala": "🐨 Koala",
        "animal_owl": "🦉 Bayıwlı",
        "animal_shark": "🦈 Akula",
        "animal_cheetah": "🐆 Gepard",
        "animal_giraffe": "🦒 Jıraf",
        "animal_elephant": "🐘 Pil",
        "animal_cat": "🐱 Pishiq",
        "animal_kangaroo": "🦘 Kenguru",

        # ===== RANKED/PRACTICE QUIZZES =====
        "btn_publish_practice": "📚 Praktikalıq retinde járiyalaw",
        "btn_publish_ranked": "🏆 Reytinglik retinde járiyalaw",
        "btn_keep_draft": "🗃 Shınıq retinde qaldırıw",
        "choose_publish_mode": "📤 <b>Járiyalaw rejimin tańlań:</b>\n\n📚 <b>Praktikalıq</b> — sheklenbegen imkaniyatlar, reytingge tásir etpeydi\n🏆 <b>Reytinglik</b> — 1 imkaniyat, reytingge tásir etedi, waqtı sheklengen",
        "btn_start_now": "▶️ Házir baslaw",
        "btn_schedule_start": "🗓 Waqıttı tańlaw",
        "choose_ranked_start": "🗓 <b>Reytinglik kvizdi qashannan baslaw?</b>\n\n▶️ Házir baslaw — 48 saǵat ámellik\n🗓 Waqıttı tańlaw — kelshekkige josparlаw",
        "enter_ranked_start_time": "🗓 Baslanıw datası hám waqıtın kirgiziń\n\nFormat: <code>DD.MM HH:MM</code>\nMásel: <code>30.01 18:00</code>",
        "invalid_datetime_format": "❌ Data formatı durıs emes.\n\nPaydalanıń: DD.MM HH:MM\nMásel: 30.01 18:00",
        "quiz_scheduled": "✅ Reytinglik kviz josparlаndı!\n\n📝 {title}\n📅 Baslanıwı: {start}\n⏰ Tamamlanıwı: {end}\n\nOqıwshılar bul waqıtta kvizdi ótiwi múmkin.",
        "quiz_published_practice": "✅ Praktikalıq kviz járiyalandı!\n\n📝 {title}\nOqıwshılar onı shegarasız múddetke ótiwi múmkin.",
        "quiz_not_started": "⏳ Bul kviz áli baslanbadı.\n\n📅 Baslanıwı: {start}",
        "quiz_expired": "⏰ Bul kvizdi ótiw waqtı tamam boldı.",
        "quiz_max_attempts": "⚠️ Siz bul kviz ushın barlıq imkaniyatlarınızdan paydalandıńız.",
        "ranked_section_header": "🏆 <b>Reytinglik kvizler</b>\n\n",
        "practice_section_header": "\n📚 <b>Praktikalıq kvizler</b>\n\n",
        "quiz_ranked_badge": "🏆",
        "quiz_practice_badge": "📚",
        "quiz_exam_mode_result": "🎉 <b>Kviz tamamlandı!</b>\n\n✅ Sizdiń nátiyjeńiz: <b>{score}/{total}</b>\n\n📊 Durıs juwaplar kviz waqtı bitkennen keyin kórsetiledi.",
        "no_ranked_quizzes": "📭 Házir aktiv reytinglik kvizler joq.",
        "no_practice_quizzes": "📭 Praktikalıq kvizler áli joq.",
        "new_ranked_quiz_notification": "🏆 <b>Jańa reytinglik kviz!</b>\n\n📝 {title}\n📅 Baslanıwı: {start}\n⏰ Tamamlanıwı: {end}\n\nSizde tek <b>bir imkaniyat</b> bar. Nátiyje reytingge tásir etedi!",

        # ===== MENU HEADERS =====
        "quiz_management_header": "📝 <b>Kvizlerdi basqarıw</b>\n\nKategoriya tańlań:",
        "quiz_student_header": "📝 <b>Kvizler</b>\n\nKategoriya tańlań:",
        "btn_active_quizzes": "📝 Aktiv kvizler",
        "btn_archived_quizzes": "🗄️ Arxivlengen kvizler",
        "btn_ranked_quizzes": "🏆 Reytinglik kvizler",
        "btn_practice_quizzes": "📚 Praktikalıq kvizler",
        "active_quizzes_header": "📝 <b>Aktiv kvizler</b>",
        "archived_quizzes_header": "🗄️ <b>Arxivlengen kvizler</b>",
        "ranked_quizzes_header": "🏆 <b>Reytinglik kvizler</b>",
        "practice_quizzes_header": "📚 <b>Praktikalıq kvizler</b>",
        "pagination_info": "<i>Bet {page}/{total} • Barlıǵı: {count}</i>",
        "no_active_quizzes": "📭 Áli aktiv kvizler joq.",
        "no_archived_quizzes": "📭 Arxivlengen kvizler joq.",
        "error_mentor_not_found": "⚠️ Qátelik: mentor tabılmadı",
        "btn_back_short": "◀️ Artqa",
        "btn_archived_short": "🗄️ Arxivlengen",
        "btn_active_short": "📝 Aktiv",
        "btn_ranked_short": "🏆 Reytinglik",
        "btn_practice_short": "📚 Praktikalıq",
    },

    "en": {
        # ===== LANGUAGE =====
        "choose_language": "🌐 Choose language:",
        "language_changed": "✅ Language changed to English",
        "btn_language": "🌐 Language",

        # ===== MONTHS =====
        "month_1": "January",
        "month_2": "February",
        "month_3": "March",
        "month_4": "April",
        "month_5": "May",
        "month_6": "June",
        "month_7": "July",
        "month_8": "August",
        "month_9": "September",
        "month_10": "October",
        "month_11": "November",
        "month_12": "December",

        # ===== START =====
        "welcome_mentor": "👋 Welcome, {name}!\n\nYou can upload and manage lesson materials.",
        "welcome_student": "👋 Welcome to StudyMate!\n\n📚 Your mentor: {name}\n\n<b>Bot features:</b>\n📚 Lesson materials — download files and documents\n📝 Quizzes — take ranked and practice tests\n❓ Questions — ask your mentor anonymously\n🏆 Leaderboard — track your results",
        "access_denied": "⛔ Access denied.\n\nYou must be a member of a course group.\nContact your mentor.",
        
        # ===== MENU BUTTONS =====
        "btn_upload": "📤 Upload",
        "btn_manage": "📂 Manage",
        "btn_view": "📚 Materials",
        "btn_materials_menu": "📚 Materials",
        "btn_statistics": "📊 Statistics",
        "btn_questions": "❓ Questions",
        "btn_lesson_materials": "📚 Materials",
        "btn_ask_question": "❓ Ask Question",
        "btn_cancel": "❌ Cancel",
        "btn_back_menu": "⬅️ Back",
        "btn_profile": "👤 Profile",

        # ===== MATERIALS SUBMENU =====
        "materials_submenu_header": "📚 <b>Materials Management</b>\n\nChoose an action:",

        # ===== STUDENT PROFILE =====
        "profile_setup_welcome": "👋 <b>Welcome!</b>\n\n📝 Please enter your full name for academic tracking.\n\nℹ️ <b>Important:</b>\n• Only your mentor will see your name\n• You'll remain anonymous to other students in the leaderboard\n• You can change your name anytime",
        "profile_enter_fullname": "📝 Enter your full name:\n\n<i>You can use Cyrillic or Latin characters</i>",
        "profile_name_too_short": "❌ Name is too short. Please enter at least 3 characters.",
        "profile_name_too_long": "❌ Name is too long. Maximum 200 characters.",
        "profile_name_invalid": "❌ Name contains invalid characters. Use only letters, spaces, and hyphens.",
        "profile_completed": "✅ <b>Profile completed!</b>\n\n📝 Your name: <b>{name}</b>\n\nYou can now use all bot features.",
        "profile_view": "👤 <b>Your Profile</b>\n\n📝 Full Name: <b>{name}</b>\n📱 Telegram: {telegram}\n📅 Joined: {joined}\n🌐 Language: {language}\n📊 Mentor: {mentor}\n\n📈 <b>Statistics</b>\n━━━━━━━━━━━━━━━\n📚 Total Quizzes: <b>{total_quizzes}</b>\n  ├ 🏆 Ranked: {total_ranked}\n  └ 📝 Practice: {total_practice}\n\n📊 Average Score: <b>{avg_percentage}%</b>\n🎯 Best Result: <b>{best_score}/{best_total}</b> ({best_percentage}%)\n\n{streak_emoji} <b>Streak</b>\n━━━━━━━━━━━━━━━\n🔥 Current: <b>{current_streak} days</b>\n🏅 Record: <b>{longest_streak} days</b>",
        "profile_not_set": "not set",
        "btn_use_telegram_name": "✅ Use Telegram name",
        "btn_edit_profile": "✏️ Edit name",
        "profile_edit_prompt": "✏️ Enter new full name:",
        "profile_updated": "✅ Name updated!",
        
        # ===== UPLOAD =====
        "choose_topic_upload": "📤 Choose topic for upload:",
        "create_new_topic": "➕ New Topic",
        "enter_topic_name": "📝 Enter topic name (e.g., HTML, CSS, JavaScript):",
        "topic_created": "✅ Topic '{name}' created!\n\nNow use 📤 Upload to add files.",
        "send_file": "📁 Topic: {name}\n\n📎 Send a file (PDF, Word, image, etc.)",
        "file_received": "📝 File received: {name}\n\nEnter a title for this material:",
        "photo_received": "📝 Photo received!\n\nEnter a title for this material:",
        "material_added": "✅ Material added!\n\n📁 Topic: {topic}\n📄 Title: {title}",
        
        # ===== MANAGE =====
        "no_topics": "📭 No topics yet. Use 📤 Upload to create one.",
        "select_topic_manage": "📂 Select topic to manage:",
        "tap_to_delete": "📂 <b>{name}</b>\n\nTap on file to delete:",
        "no_topics_left": "📭 No topics left.",
        
        # ===== DELETE CONFIRMATION =====
        "confirm_delete_file": "🗑️ <b>Delete this file?</b>\n\n📄 {title}",
        "btn_yes_delete": "✅ Yes",
        "btn_no_cancel": "❌ No",
        "file_deleted": "✅ File deleted!",
        "confirm_delete_topic": "⚠️ <b>Delete entire topic?</b>\n\n📁 {name}\n📄 {count} file(s) will be deleted\n\nThis cannot be undone!",
        "btn_yes_delete_all": "✅ Yes, delete",
        "topic_deleted": "✅ Topic '{name}' deleted!",
        
        # ===== VIEW MATERIALS =====
        "your_materials": "📚 <b>Your materials:</b>",
        "lesson_materials": "📚 <b>Lesson Materials</b>\n\nSelect a topic:",
        "no_materials": "📭 No materials yet.",
        "no_materials_yet": "📭 No materials yet.\n\nCheck back later!",
        "topic_files": "📂 <b>{name}</b>\n\n📄 {count} material(s)\n\nTap to download:",
        "file_sent": "✅ Sent!",
        "file_not_found": "❌ File not found",
        "btn_back": "⬅️ Back",
        "btn_back_topics": "⬅️ To Topics",
        "btn_prev": "◀️",
        "btn_next": "▶️",
        
        # ===== STATISTICS =====
        "statistics": "📊 <b>Statistics</b>\n\n",
        "stats_students": "👥 Students: <b>{count}</b>\n",
        "stats_topics": "📁 Topics: <b>{count}</b>\n",
        "stats_materials": "📄 Materials: <b>{count}</b>\n",
        "stats_questions": "❓ Questions: <b>{total}</b>",
        "stats_unanswered": " ({count} unanswered)",
        "stats_active_today": "📈 Active today: <b>{count}</b>\n",
        "stats_active_week": "📅 Active this week: <b>{count}</b>\n",
        "stats_popular": "\n🔥 <b>Popular materials:</b>\n",
        "stats_popular_item": "{num}. {title} — {count} downloads\n",
        
        # ===== QUESTIONS =====
        "write_question": "✏️ Write your question.\n\nYour name will NOT be shown to the teacher.",
        "question_sent": "✅ Question sent!",
        "cancelled": "❌ Cancelled",
        "no_questions": "📭 No new questions.\n\nQuestions from students will appear here.",
        "unanswered_questions": "❓ Unanswered questions ({count}):\n\n",
        "anonymous_question": "❓ <b>Anonymous question:</b>\n\n{text}",
        "btn_answered": "✅ Answered",
        "btn_reply": "💬 Reply",
        "marked_answered": "✅ Marked!",
        "and_more": "...and {count} more.",
        "write_reply": "✏️ Write your reply to the question:\n\n<b>Question:</b> {text}",
        "reply_sent": "✅ Reply sent to the student!",
        "mentor_reply": "💬 <b>Reply from your mentor:</b>\n\n{text}",
        "question_not_found": "❌ Question not found",
        
        # ===== ERRORS =====
        "error": "⚠️ Error. Use /start",
        "not_assigned": "⚠️ You are not assigned to a mentor. Use /start",
        "throttle_warning_1": "⏱ Please wait a bit before next action",
        "throttle_warning_2": "⏱ You're sending messages too fast. Please wait.",
        "throttle_warning_3": "⚠️ Please don't spam. Wait a few seconds.",

        # ===== MANAGE FILES =====
        "btn_delete_topic": "🗑️ Delete Topic",

        # ===== QUIZZES =====
        "btn_quizzes": "📝 Quizzes",
        "no_quizzes": "📭 No quizzes yet.",
        "select_quiz": "📝 Select a quiz:",
        "upload_quiz": "📄 Send a .txt file with the quiz.",
        "quiz_uploaded": "✅ Quiz '{title}' created!\n\n📊 Questions: {count}",
        "quiz_parse_error": "❌ File parsing error. Check the format.",
        "quiz_question": "❓ <b>Question {current}/{total}</b>\n\n{text}\n\nA) {a}\nB) {b}\nC) {c}\nD) {d}",
        "quiz_finished": "🎉 <b>Quiz completed!</b>\n\n✅ Your result: <b>{score}/{total}</b>\n📊 Group average: <b>{avg}</b>",
        "quiz_review_header": "\n\n📋 <b>Your answers:</b>\n",
        "quiz_review_header_page": "\n\n📋 <b>Your answers (page {page}/{total_pages}):</b>\n",
        "quiz_review_correct": "✅ {num}. {question}\n   Your answer: <b>{answer}</b> ✓\n",
        "quiz_review_wrong": "❌ {num}. {question}\n   Your answer: <b>{answer}</b> | Correct: <b>{correct}</b>\n",
        "quiz_results": "📊 <b>Results: {title}</b>\n\n👥 Completed: {attempts}\n📈 Average score: {avg}\n\n🏆 <b>Top students:</b>\n{top}",
        "quiz_no_attempts": "No one has taken this quiz yet.",
        "quiz_your_result": "Your result: {score}/{total}",
        "quiz_not_attempted": "Not attempted yet",
        "quiz_already_taken": "⚠️ You have already taken this quiz.\n\nYour result: {score}/{total}",
        "quiz_view_answers": "📋 View answers",
        "quiz_retake": "🔄 Retake quiz",
        "quiz_time_expired": "⏱ Time expired",
        "quiz_seconds": "sec.",
        "quiz_in_progress": "⏳ You are currently taking a quiz!\n\nPlease finish the current quiz to access other bot functions.",
        "btn_upload_quiz": "📤 Upload Quiz",
        "btn_delete_quiz": "🗑️ Delete Quiz",
        "btn_quiz_results": "📊 Results",
        "btn_save_quiz": "✅ Save",
        "btn_cancel_quiz": "❌ Cancel",
        "btn_replace_quiz": "🗄️ Archive and replace",
        "btn_copy_quiz": "➕ Create copy",
        "btn_archive_quiz": "🗄️ Archive",
        "btn_unarchive_quiz": "♻️ Restore from archive",
        "btn_restart_quiz": "🔄 Restart quiz",
        "btn_manage_questions": "📋 Manage questions",
        "btn_export_results": "📤 Export results",
        "btn_add_question": "➕ Add question",
        "btn_edit_question": "✏️ Edit",
        "btn_delete_question": "🗑️ Delete question",
        "btn_back_quiz": "⬅️ Back to quiz",
        "btn_back_questions": "⬅️ Back to list",
        "btn_edit_text": "✏️ Question text",
        "btn_edit_option_a": "A) Option A",
        "btn_edit_option_b": "B) Option B",
        "btn_edit_option_c": "C) Option C",
        "btn_edit_option_d": "D) Option D",
        "btn_edit_correct": "✅ Correct answer",
        "confirm_delete_quiz": "🗑️ <b>Delete quiz?</b>\n\n📝 {title}\n❓ {count} questions\n\nAll student results will be deleted!",
        "quiz_preview": "👀 <b>Quiz preview</b>\n\n📝 {title}\n📌 Topic: {topic}\n❓ Questions: {count}\n\n{preview}",
        "quiz_preview_question": "1) {text}\nA) {a}\nB) {b}\nC) {c}\nD) {d}",
        "quiz_duplicate_found": "⚠️ A quiz titled “{title}” already exists. Choose an action:",
        "quiz_ready_actions": "Choose an action from the menu.",
        "confirm_archive_quiz": "🗄️ <b>Archive quiz?</b>\n\n📝 {title}\n❓ {count} questions",
        "confirm_restart_quiz": "🔄 <b>Restart quiz?</b>\n\n📝 {title}\n\n⚠️ All student attempts will be deleted!\n🔀 Questions will be shuffled randomly.\n\nContinue?",
        "quiz_restarted": "✅ Quiz restarted! Questions shuffled.",
        "quiz_deleted": "✅ Quiz deleted!",
        "quiz_archived": "🗄️ Quiz archived.",
        "quiz_unarchived": "♻️ Quiz restored from archive.",
        "quiz_questions_title": "📋 <b>{title}</b>\n\nQuestions: {count}",
        "quiz_question_detail": "❓ <b>Question</b>\n\n{question}\n\nA) {a}\nB) {b}\nC) {c}\nD) {d}\n\n<b>Correct:</b> {correct}",
        "enter_question_text": "❓ Enter the question text:",
        "enter_option_a": "A) Enter option A:",
        "enter_option_b": "B) Enter option B:",
        "enter_option_c": "C) Enter option C:",
        "enter_option_d": "D) Enter option D:",
        "enter_correct_option": "Enter the correct option letter (A/B/C/D):",
        "invalid_correct_option": "❌ Please enter A, B, C, or D.",
        "question_added": "✅ Question added!",
        "confirm_delete_question": "🗑️ <b>Delete question?</b>\n\n{text}",
        "question_deleted": "✅ Question deleted!",
        "question_updated": "✅ Question updated!",
        "quiz_edit_prompt": "✏️ What do you want to change?",
        "quiz_export_ready": "📤 Done! Results file attached.",
        "quiz_export_empty": "🗒️ No attempts yet.",
        "quiz_mentor_list": "📝 <b>Your quizzes:</b>",
        "quiz_item_mentor": "📝 {title} • {questions} q. • {attempts} attempts",
        "quiz_item_student": "📝 {title}",
        "quiz_item_student_score": "📝 {title} • {score}/{total}",

        # ===== LEADERBOARD =====
        "btn_leaderboard": "🏆 Leaderboard",
        "leaderboard_title": "🏆 <b>Student Rankings</b>\n\n",
        "leaderboard_entry": "{medal} {name} — <code>{score}</code>\n",
        "leaderboard_you": "{medal} <b>YOU</b> — <code>{score}</code>\n",
        "leaderboard_footer": "",
        "leaderboard_empty": "📭 Leaderboard is empty. Take quizzes to get on the board!",
        "leaderboard_your_rank": "\n<b>━━━━━━━━━━━━━━━</b>\n📍 <b>Your rank:</b> #{rank}\n💯 <b>Score:</b> <code>{score}</code>",
        "leaderboard_separator_top3": "\n<b>━━━━━━━━━━━━━━━</b>\n",
        "leaderboard_mentor_title": "🏆 <b>Student Rankings</b>\n\n",
        "leaderboard_mentor_entry": "{rank}. {name} — {score} pts\n   📊 {percentage}% avg • {quizzes} quiz.\n",
        "leaderboard_mentor_pagination": "Total students: {total} • Page {page}/{total_pages}",

        # Animal names for anonymization
        "animal_fox": "🦊 Fox",
        "animal_bear": "🐻 Bear",
        "animal_eagle": "🦅 Eagle",
        "animal_wolf": "🐺 Wolf",
        "animal_lion": "🦁 Lion",
        "animal_tiger": "🐯 Tiger",
        "animal_panda": "🐼 Panda",
        "animal_koala": "🐨 Koala",
        "animal_owl": "🦉 Owl",
        "animal_shark": "🦈 Shark",
        "animal_cheetah": "🐆 Cheetah",
        "animal_giraffe": "🦒 Giraffe",
        "animal_elephant": "🐘 Elephant",
        "animal_cat": "🐱 Cat",
        "animal_kangaroo": "🦘 Kangaroo",

        # ===== RANKED/PRACTICE QUIZZES =====
        "btn_publish_practice": "📚 Publish as Practice",
        "btn_publish_ranked": "🏆 Publish as Ranked",
        "btn_keep_draft": "🗃 Keep as Draft",
        "choose_publish_mode": "📤 <b>Choose publishing mode:</b>\n\n📚 <b>Practice</b> — unlimited attempts, doesn't affect leaderboard\n🏆 <b>Ranked</b> — 1 attempt, affects leaderboard, limited time",
        "btn_start_now": "▶️ Start now",
        "btn_schedule_start": "🗓 Choose time",
        "choose_ranked_start": "🗓 <b>When to start ranked quiz?</b>\n\n▶️ Start now — available for 48 hours\n🗓 Choose time — schedule for future",
        "enter_ranked_start_time": "🗓 Enter start date and time\n\nFormat: <code>DD.MM HH:MM</code>\nExample: <code>30.01 18:00</code>",
        "invalid_datetime_format": "❌ Invalid date format.\n\nUse: DD.MM HH:MM\nExample: 30.01 18:00",
        "quiz_scheduled": "✅ Ranked quiz scheduled!\n\n📝 {title}\n📅 Start: {start}\n⏰ End: {end}\n\nStudents will be able to take the quiz during this time.",
        "quiz_published_practice": "✅ Practice quiz published!\n\n📝 {title}\nStudents can take it unlimited times.",
        "quiz_not_started": "⏳ This quiz hasn't started yet.\n\n📅 Start: {start}",
        "quiz_expired": "⏰ Time to take this quiz has expired.",
        "quiz_max_attempts": "⚠️ You've used all attempts for this quiz.",
        "ranked_section_header": "🏆 <b>Ranked Quizzes</b>\n\n",
        "practice_section_header": "\n📚 <b>Practice Quizzes</b>\n\n",
        "quiz_ranked_badge": "🏆",
        "quiz_practice_badge": "📚",
        "quiz_exam_mode_result": "🎉 <b>Quiz completed!</b>\n\n✅ Your result: <b>{score}/{total}</b>\n\n📊 Correct answers will be shown after the quiz time ends.",
        "no_ranked_quizzes": "📭 No active ranked quizzes right now.",
        "no_practice_quizzes": "📭 No practice quizzes yet.",
        "new_ranked_quiz_notification": "🏆 <b>New ranked quiz!</b>\n\n📝 {title}\n📅 Start: {start}\n⏰ End: {end}\n\nYou have only <b>one attempt</b>. The result will affect the leaderboard!",

        # ===== MENU HEADERS =====
        "quiz_management_header": "📝 <b>Quiz Management</b>\n\nChoose category:",
        "quiz_student_header": "📝 <b>Quizzes</b>\n\nChoose category:",
        "btn_active_quizzes": "📝 Active Quizzes",
        "btn_archived_quizzes": "🗄️ Archived Quizzes",
        "btn_ranked_quizzes": "🏆 Ranked Quizzes",
        "btn_practice_quizzes": "📚 Practice Quizzes",
        "active_quizzes_header": "📝 <b>Active Quizzes</b>",
        "archived_quizzes_header": "🗄️ <b>Archived Quizzes</b>",
        "ranked_quizzes_header": "🏆 <b>Ranked Quizzes</b>",
        "practice_quizzes_header": "📚 <b>Practice Quizzes</b>",
        "pagination_info": "<i>Page {page}/{total} • Total: {count}</i>",
        "no_active_quizzes": "📭 No active quizzes yet.",
        "no_archived_quizzes": "📭 No archived quizzes.",
        "error_mentor_not_found": "⚠️ Error: mentor not found",
        "btn_back_short": "◀️ Back",
        "btn_archived_short": "🗄️ Archived",
        "btn_active_short": "📝 Active",
        "btn_ranked_short": "🏆 Ranked",
        "btn_practice_short": "📚 Practice",
    },
}

DEFAULT_LANG = "ru"


def t(key: str, lang: str = None, **kwargs) -> str:
    """Get text by key with optional formatting"""
    if lang is None:
        lang = DEFAULT_LANG
    text = TEXTS.get(lang, TEXTS[DEFAULT_LANG]).get(key, key)
    return text.format(**kwargs) if kwargs else text


def get_season_name(season, lang: str = None) -> str:
    """
    Generate season name dynamically based on user language.

    Args:
        season: Season object with start_date attribute
        lang: User language code (ru, qq, en)

    Returns:
        Localized season name (e.g., "Февраль 2026", "February 2026")
    """
    if lang is None:
        lang = DEFAULT_LANG

    # Get month name from translations
    month_key = f"month_{season.start_date.month}"
    month_name = t(month_key, lang)

    # Format: "Month Year" (e.g., "Февраль 2026")
    return f"{month_name} {season.start_date.year}"
