# Generated by Django 6.0.1 on 2026-01-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='language',
            field=models.CharField(default='ru', max_length=5, verbose_name='Language'),
        ),
    ]
