# Generated by Django 6.0.1 on 2026-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['topic', 'created_at'], name='materials_m_topic_i_c03f8e_idx'),
        ),
    ]
